// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN2OdYHWf1yWxRJ1KfUQEUTCTRs4RAYLI',
    appId: '1:527632739274:web:4f7a62b8a4a95995123d33',
    messagingSenderId: '527632739274',
    projectId: 'proyectofinaltp3',
    authDomain: 'proyectofinaltp3.firebaseapp.com',
    storageBucket: 'proyectofinaltp3.appspot.com',
    measurementId: 'G-J5G9F6WG2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Yc3qWKNNmI6Vao5QVza101irj5GDspw',
    appId: '1:527632739274:android:9b38e8537258764a123d33',
    messagingSenderId: '527632739274',
    projectId: 'proyectofinaltp3',
    storageBucket: 'proyectofinaltp3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxsrv-OVbE4INi7ih5oIrogPiD38vp8hA',
    appId: '1:527632739274:ios:21506a421c0f8561123d33',
    messagingSenderId: '527632739274',
    projectId: 'proyectofinaltp3',
    storageBucket: 'proyectofinaltp3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxsrv-OVbE4INi7ih5oIrogPiD38vp8hA',
    appId: '1:527632739274:ios:21506a421c0f8561123d33',
    messagingSenderId: '527632739274',
    projectId: 'proyectofinaltp3',
    storageBucket: 'proyectofinaltp3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN2OdYHWf1yWxRJ1KfUQEUTCTRs4RAYLI',
    appId: '1:527632739274:web:e7fe0fbe1e0a30a0123d33',
    messagingSenderId: '527632739274',
    projectId: 'proyectofinaltp3',
    authDomain: 'proyectofinaltp3.firebaseapp.com',
    storageBucket: 'proyectofinaltp3.appspot.com',
    measurementId: 'G-FPQ4M8SGCZ',
  );
}
